version: '3.4'
services:
  prometheus:
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    hostname: prometheus
    container_name: localprometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom_volume/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION}"
    container_name: localgrafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_volume/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_volume/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./grafana.db:/var/lib/grafana/grafana.db
    depends_on:
      - prometheus
    links:
      - prometheus
    restart: always
